// Generated by CoffeeScript 1.3.3
(function() {

  window.node = function(nameOrNode, oncreate) {
    var name, newNode, tag;
    if (nameOrNode instanceof Node) {
      newNode = nameOrNode;
    } else {
      name = nameOrNode;
      tag = (function() {
        switch (name) {
          case "a":
          case "abbr":
          case "acronym":
          case "address":
          case "applet":
          case "area":
          case "article":
          case "aside":
          case "audio":
          case "b":
          case "bdi":
          case "base":
          case "basefont":
          case "bdo":
          case "big":
          case "blockquote":
          case "body":
          case "br":
          case "button":
          case "canvas":
          case "caption":
          case "center":
          case "cite":
          case "code":
          case "col":
          case "colgroup":
          case "command":
          case "data":
          case "datagrid":
          case "datalist":
          case "dd":
          case "del":
          case "details":
          case "dfn":
          case "dir":
          case "div":
          case "dl":
          case "dt":
          case "em":
          case "embed":
          case "eventsource":
          case "fieldset":
          case "figcaption":
          case "figure":
          case "font":
          case "footer":
          case "form":
          case "frame":
          case "frameset":
          case "h1":
          case "h2":
          case "h3":
          case "h4":
          case "h5":
          case "h6":
          case "head":
          case "header":
          case "hgroup":
          case "hr":
          case "html":
          case "i":
          case "iframe":
          case "img":
          case "input":
          case "ins":
          case "isindex":
          case "kbd":
          case "keygen":
          case "label":
          case "legend":
          case "li":
          case "link":
          case "mark":
          case "map":
          case "menu":
          case "meta":
          case "meter":
          case "nav":
          case "noframes":
          case "noscript":
          case "object":
          case "ol":
          case "optgroup":
          case "option":
          case "output":
          case "p":
          case "param":
          case "pre":
          case "progress":
          case "q":
          case "ruby":
          case "rp":
          case "rt":
          case "s":
          case "samp":
          case "script":
          case "section":
          case "select":
          case "small":
          case "source":
          case "span":
          case "strike":
          case "strong":
          case "style":
          case "sub":
          case "summary":
          case "sup":
          case "table":
          case "tbody":
          case "td":
          case "textarea":
          case "tfoot":
          case "th":
          case "thead":
          case "time":
          case "title":
          case "tr":
          case "track":
          case "tt":
          case "u":
          case "ul":
          case "var":
          case "video":
          case "wbr":
            return name;
          default:
            return "div";
        }
      })();
      newNode = document.createElement(tag);
      newNode.className = name;
    }
    newNode.oncreate = oncreate;
    if (newNode.oncreate != null) {
      newNode.oncreate();
    }
    return newNode;
  };

  Node.prototype.node = function(name, oncreate) {
    var newNode;
    newNode = window.node(name, oncreate);
    this.appendChild(newNode);
    return newNode;
  };

  Node.prototype.text = function(value) {
    return this.appendChild(document.createTextNode(value));
  };

  Node.prototype.attribute = function(name, value) {
    return this.setAttribute(name, value);
  };

  /* --------------------------------------------
       Begin main.coffee
  --------------------------------------------
  */


  document.body.node("background");

  document.body.node("header");

  document.body.node("article");

}).call(this);
